spring.application.name=app

spring.datasource.url=jdbc:postgresql://localhost:5432/pomato
spring.datasource.username=postgres
spring.datasource.password=102938150799

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=user
spring.security.user.password=123456
logging.level.org.springframework.security=DEBUG
jwt.secret=QUJISU1BTllVMTUwNzpQQVBB
jwt.expiration=3600000  